{{- if .Values.authorizationPolicy.enabled }}
# AuthorizationPolicy template
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.authorizationPolicy.name }}-authorization-policy
  namespace: {{ .Values.authorizationPolicy.namespace }}
  labels:
    app: {{ .Values.authorizationPolicy.app }}
spec:
    selector:
        matchLabels:
        app: {{ .Values.authorizationPolicy.app }}
    action: {{ .Values.authorizationPolicy.action }}
    rules:
    {{- range .Values.authorizationPolicy.rules }}
    - from:
        {{- range .from }}
        - source:
            {{ with .principals }}
            methods:
            {{- range . }}
            - {{ . }}
            {{- end }}
            {{- end }}
            {{ with .notPrincipals }}
            notPrincipals:
            {{- range . }}
            - {{ . }}
            {{- end }}
            {{- end }}
            {{ with .namespaces }}
            namespaces:
            {{- range . }}
            - {{ . }}
            {{- end }}
            {{- end }}
            {{ with .ipBlocks }}
            ipBlocks:
            {{- range . }}
            - {{ . }}
            {{- end }}
            {{- end }}
            {{ with .notIpBlocks }}
            notIpBlocks:
            {{- range . }}
            - {{ . }}
            {{- end }}
            {{- end }}
        {{- end }}
        {{- range .to }}
        - operation:
            {{ with .methods }}
            methods:
            {{- range . }}
            - {{ . }}
            {{- end }}
            {{- end }}
            {{ with .paths }}
            paths:
            {{- range . }}
            - {{ . }}
            {{- end }}
            {{- end }}
        {{- end }}
        {{- range .when }}
        - when:
            {{- range .key }}
            key: {{ . }}
            {{- end }}
            {{- range .values }}
            values:
            - {{ . }}
            {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
