{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.chartName }}-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appName }}
      role: {{ .Values.deployment.role }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appName }}
        role: {{ .Values.deployment.role }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: "{{ .Values.deployment.imageRepository }}:{{ .Values.deployment.imageTag }}"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: {{ .Values.deployment.port }}
{{- end }}
