{{- if .Values.peerAuthentication.enabled }}
# Peer Authentication template
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.global.chartName }}-peer-authentication
  namespace: {{ .Values.peerAuthentication.namespace }}
spec:
    selector:
      matchLabels:
        {{- if .Values.peerAuthentication.app }}
        app: {{ .Values.peerAuthentication.app  }}
        {{- end }}
        {{- if .Values.peerAuthentication.workload }}
        workload: {{ .Values.peerAuthentication.workload }}
        {{- end }}
    mtls:
      # https://istio.io/latest/docs/reference/config/security/peer_authentication/#PeerAuthentication-MutualTLS-Mode
      # options: STRICT, PERMISSIVE, DISABLE
      mode: {{ .Values.peerAuthentication.mtls.mode | default "PERMISSIVE" }}
{{- end }}
