{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}-vs
  namespace: {{ .Values.virtualService.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  # defaulted to asm-ingress/asm-ingress-gateway for demo purposes
  # otherwise, use the gateway name you created or default org gateway
  - {{ default "asm-ingress/asm-ingress-gateway" .Values.virtualService.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    headers:
      request:
        add:
          x-request-id: request.headers['x-request-id']
          x-envoy-decorator-operation: request.headers['x-envoy-decorator-operation']
      response:
        add:
          x-request-id: request.headers['x-request-id']
          x-envoy-decorator-operation: request.headers['x-envoy-decorator-operation']
    route:
    - destination:
        host: {{ .Values.virtualService.destination.host }}
        port:
          number: {{ .Values.virtualService.destination.port }}
    retries:
      attempts: 3
      perTryTimeout: 2s
    timeout: 10s
{{- end }}
