global:
  chartName: fastapi
  namespace: python
fastapi:
  # Deployment object
  deployment:
    enabled: false
  # Updated (New) Deployment resource
  newDeployment:
    enabled: true
    replicas: 1
    appName: fastapi
    role: api
    containerName: fastapi-container
    imageRepository: eleazarharold/fastapi-python
    imageTag: "v5"
    port: 8000
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
  # Stable Service object
  service:
    enabled: true
    appName: fastapi
    type: ClusterIP
    servicePort: 8000
    targetPort: 8000
  # Canary Service object (for Argo Rollouts)
  canaryService:
    enabled: false
  # Namespace object
  namespace:
    enabled: true
    name: python
  # Ingress
  ingress:
    enabled: false
  # Canary Rollout # Canary Service object (for Argo Rollouts)
  canaryRollout:
    enabled: false
  # Virtual Service
  virtualService:
    enabled: true
    destination:
      port: 8000
  # Peer Authentication
  peerAuthentication:
    enabled: true
    app: fastapi
    mtls:
      mode: STRICT
  # Authorization Policy
  authorizationPolicy:
  # get authorization policy attributes from platform/istio/authorization-policy.yaml
    enabled: true
    app: fastapi
    action: ALLOW
    rules:
      - from:
        - namespaces:
          - express
        to:
        - methods:
          - GET
          - POST
  # Request Authentication
  requestAuthentication:
    enabled: false
  # Service Entry
  serviceEntry:
    enabled: false
  # Envoy Filter
  envoyFilter:
    enabled: true
    workloadSelector:
      labels:
        app: fastapi
    configPatches:
    - applyTo: "HTTP_FILTER"
      match:
        context: "SIDECAR_INBOUND"
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: "INSERT_BEFORE"
        value:
          name: "envoy.lua"
          typed_config: |
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                local headers = request_handle:headers()
                local service = headers:get(":authority")
                local namespace = headers:get("x-istio-namespace")
                if namespace == "express" and service == "nodejs-service" then
                  headers:add("x-call-service", service .. "." .. namespace .. ".svc.cluster.local")
                  request_handle:logInfo("nodejs-service called fastapi-service successfully")
                else
                  request_handle:logWarn("Service and/or Namespace are incorrect")
                end
              end
